// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5cOs3kCAbaIib45c212uGzdwJtxVCeU',
    appId: '1:933212537172:ios:5f8a3946ad5d790e9708c1',
    messagingSenderId: '933212537172',
    projectId: 'ctisims-5e282',
    storageBucket: 'ctisims-5e282.firebasestorage.app',
    iosBundleId: 'com.example.ctisims',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXZZKSXan-2kfovgfuJf1hinFjWhuH2Hc',
    authDomain: 'ctisims-5e282.firebaseapp.com',
    projectId: 'ctisims-5e282',
    storageBucket: 'ctisims-5e282.firebasestorage.app',
    messagingSenderId: '933212537172',
    appId: '1:933212537172:web:ac330ebf644919859708c1',
    measurementId: 'G-WQELMRF8NW',
  );

}